DROP TABLE IF EXISTS A3_ISSUE;
DROP TABLE IF EXISTS A3_USER;

CREATE TABLE A3_USER
(
	USER_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(100) NOT NULL,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL
);

INSERT INTO A3_USER (USERNAME,FIRSTNAME,LASTNAME) VALUES ('-','not','assigned');			-- 1
INSERT INTO A3_USER (USERNAME,FIRSTNAME,LASTNAME) VALUES ('Chris', 'Christopher','Smith');  -- 2
INSERT INTO A3_USER (USERNAME,FIRSTNAME,LASTNAME) VALUES ('Dave', 'David','Jones');         -- 3
INSERT INTO A3_USER (USERNAME,FIRSTNAME,LASTNAME) VALUES ('Vlad', 'Vladimir','Putin');      -- 4

CREATE TABLE A3_ISSUE
(
	ISSUE_ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100),
	DESCRIPTION VARCHAR(1000),
	CREATOR INTEGER NOT NULL REFERENCES A3_USER,
	RESOLVER INTEGER REFERENCES A3_USER,
	VERIFIER INTEGER REFERENCES A3_USER
);

BEGIN;
	INSERT INTO A3_ISSUE (TITLE,DESCRIPTION,CREATOR,RESOLVER,VERIFIER) VALUES ('Factorial with addition anomaly','Performing a factorial and then addition produces an off by 1 error',2,3,4);
	INSERT INTO A3_ISSUE (TITLE,DESCRIPTION,CREATOR,RESOLVER,VERIFIER) VALUES ('Division by zero','Division by 0 doesn''t yield error or infinity as would be expected. Instead it results in -1.',2,3,1);
	INSERT INTO A3_ISSUE (TITLE,DESCRIPTION,CREATOR,RESOLVER,VERIFIER) VALUES ('Incorrect BODMAS order','Addition occurring before multiplication',3,1,1);
COMMIT;

-- CREATE OR REPLACE FUNCTION username_to_id (IN uname VARCHAR, OUT userid INT)
-- AS 'SELECT user_id FROM A3_USER WHERE username = uname'
-- LANGUAGE SQL;

CREATE OR REPLACE FUNCTION username_to_id (IN uname VARCHAR, uid INT)
RETURNS INT AS $$
DECLARE
	uid INT;
BEGIN
	IF uname NOT IN (
		SELECT username FROM A3_USER
	) THEN RAISE EXCEPTION 'User does not exist';
	ELSE
		SELECT users.user_id INTO uid
		FROM A3_USER AS users
		WHERE users.username = uname;
	END IF;
END;
$$ LANGUAGE plpgsql;
